---
title: "FPCC2 - Laboratório 1"
author: "Thiago Chaves"
---

{r setup, include=FALSE} 
knitr::opts_chunk\$set(echo = TRUE)

# Importando dados

{r, echo = FALSE} 
library(ggplot2) 
library(scales)

source("../code/lab1.R")

# Calcule média e desvio padrão da idade e nível de interesse. As métricas contendos as métricas calculadas para idade e devem ser apresentadas de forma ordenada, da maior idade para a menor. Além de apresentar no relatório, os resultados devem ser salvos em um arquivo csv, que deve ser adicionado ao repositório.

#{r, echo=TRUE}

#df_idade <- turma_fpcc2 %>% 
#select(idade) %>% 
#mutate(idade_int = as.integer(gsub("[a-z]\|\\.", "", idade)))

#view(df_idade)

#mean(df_idade$idade_int) sd(df_idade$idade_int)

#summary(df_idade$idade_int) boxplot(df_idade$idade_int)

#Qual o curso com maior valor médio de idade? Discutir os resultados com base nos dados disponíveis em termos de representatividade. {r}

q1 <- turma_fpcc2 %>% 
select(tipo_curso, idade) %>% 
mutate(idade_int = as.integer(gsub("[a-z]|\\.", "", idade))) %>%
group_by(tipo_curso) %>% 
summarise(max(idade_int))


